config:
  send_anonymous_usage_stats: false

dbt_sandbox:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: postgres
      port: 5432
      dbname: postgres
      schema: sandbox
      threads: 4
